version: '3.8'
services:
  environment:
    - GEMINI_API_KEY=${GEMINI_API_KEY}
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # בהנחה שאתם משתמשים ב-Vite
    depends_on:
      - backend
    environment:
    - GEMINI_API_KEY=${GEMINI_API_KEY}