version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # בהנחה שאתם משתמשים ב-Vite
    depends_on:
      - backend